//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualTeensy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool updateNeeded {
            get {
                return ((bool)(this["updateNeeded"]));
            }
            set {
                this["updateNeeded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,800,1000")]
        public global::System.Windows.Rect fileWinBounds {
            get {
                return ((global::System.Windows.Rect)(this["fileWinBounds"]));
            }
            set {
                this["fileWinBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::VisualTeensy.Model.ProjectData projectData {
            get {
                return ((global::VisualTeensy.Model.ProjectData)(this["projectData"]));
            }
            set {
                this["projectData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::VisualTeensy.Model.SetupData setupData {
            get {
                return ((global::VisualTeensy.Model.SetupData)(this["setupData"]));
            }
            set {
                this["setupData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,1000,800")]
        public global::System.Windows.Rect mainWinBounds {
            get {
                return ((global::System.Windows.Rect)(this["mainWinBounds"]));
            }
            set {
                this["mainWinBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultProjectBase {
            get {
                return ((string)(this["defaultProjectBase"]));
            }
            set {
                this["defaultProjectBase"] = value;
            }
        }
    }
}
